import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import NavbarMobile from "@/components/navbarMobile";
import { Toaster } from "react-hot-toast";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${spaceGrotesk.className} antialiased bg-dark-background`}
      >
        <Toaster
          position="top-right"
          toastOptions={{
            success: {
              style: {
                background: "var(--color-light-boxes)",
                color: "var(--color-text-secondary)",
              },
            },
            error: {
              style: {
                background: "red",
                color: "#FFF",
              },
            },
          }}
        />

        <main className="w-full h-screen flex flex-col items-center">
          <div className="w-full h-full flex flex-col items-center overflow-y-auto" style={{ scrollbarWidth: "none", msOverflowStyle: "none", scrollBehavior: "smooth" }}>
            {children}
          </div>

          <NavbarMobile />
        </main>
      </body>
    </html>
  );
}
